language: go
sudo: false

go:
  - 1.11.x

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls

install:
  - GO111MODULE=off go get gitlab.com/kode4food/go-snapshot
  - GO111MODULE=off go get -u golang.org/x/tools/cmd/stringer
  - GO111MODULE=off go get -u golang.org/x/lint/golint

env:
  - GO111MODULE=on

script:
  - $GOPATH/bin/go-snapshot -pkg assets -out internal/assets/assets.go docstring/*.md bootstrap/lisp/*.lisp
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci -ignore=internal/assets/assets.go,runtime/isa/opcode_string.go,compiler/encoder/scope_string.go,data/function_string.go,data/comparison_string.go
